# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: '15.0' 

    - name: Build Swift package
      run: xcodebuild -scheme "Piyola" -configuration Release -destination 'platform=iOS Simulator,name=iPhone 15' build
      env:
        CI: true
        
    - name: Run tests
      run: xcodebuild -scheme "Piyola" test -destination 'platform=iOS Simulator,name=iPhone 12'
      env:
        CI: true

